name = "upload-video"
main = "upload_video.js"  # 移除 ./ 前缀，使用相对路径
compatibility_date = "2025-04-17"

# R2 存储桶绑定
[[r2_buckets]]
binding = "VIDEO_BUCKET"
bucket_name = "aieffi"

# 环境变量
[vars]
API_SECRET = ""  # 部署时会从环境变量中获取